### ISSUE TITLE
List option actions no longer work

### ISSUE THREAD

**Issue by Shashank066** [fbriere/mpv-scripts#2]
Profile gets applied correctly but the glsl shader line fails.

```
[anime]
profile-desc="tree:F:\Videos\Anime"

fullscreen=no
glsl-shader = E:/Softwares/Video Player/mpv.net-portable-x64-5.4.8.0/shaders/Anime4K_3.0_Upscale_CNN_M_x2_Deblur.glsl
fbo-format = rgba16hf
```

```
[tree_profiles] Loading lua script E:\Softwares\Video Player\mpv.net-portable-x64-5.4.8.0\portable_config\scripts/tree-profiles.lua...
[tree_profiles] loading mp.defaults
[tree_profiles] loading file E:\Softwares\Video Player\mpv.net-portable-x64-5.4.8.0\portable_config\scripts/tree-profiles.lua
[tree_profiles] brace-expand.lua not found -- brace expansion disabled 
[tree_profiles] luaposix not found -- falling back on alternatives 
[tree_profiles] Searching for parent profile of F:\Videos\Anime\One Punch Man\One Punch Man Season 2\5.mkv 
[tree_profiles] Trying anime (F:\Videos\Anime) 
[tree_profiles] Profile matches as a parent
[tree_profiles] Applying profile anime 
[tree_profiles] Locally applying profile "anime" (depth 1) 
[tree_profiles] Locally setting fullscreen = "no" 
[cplayer] Set property: file-local-options/fullscreen="no" -> 1
[tree_profiles] Locally setting glsl-shader = "E:/Softwares/Video Player/mpv.net-portable-x64-5.4.8.0/shaders/Anime4K_3.0_Upscale_CNN_M_x2_Deblur.glsl" 
[cplayer] Set property: file-local-options/glsl-shader="E:/Softwares/Video Player/mpv.net-portable-x64-5.4.8.0/shaders/Anime4K_3.0_Upscale_CNN_M_x2_Deblur.glsl" -> -3
[tree_profiles] Locally setting fbo-format = "rgba16hf" 

```

The same glsl shader path works in mpv.conf but not under tree-profiles.lua. Using windows 10.

**Comment by fbriere** [comment]
Indeed, this issue will occur with mpv from 0.29.0 onwards (since mpv-player/mpv@5532d8c), breaking the setting of any list option using an action suffix (e.g. `--display-tags-append`) or any alias to such an action (e.g. `--glsl-shader` being an alias to `--glsl-shader-append`).

I've already written a fix for this, but it would be incompatible with mpv 0.28.0 and earlier, which I'd like to avoid.  I have an idea on how to make it work for everyone, but this will require some more time and a lot more testing, so it might take a while.

In the meantime, you can step around this issue entirely by setting the list option directly &mdash; `glsl-shaders` in your case (note the plural form):

```
glsl-shaders="E:/Softwares/Video Player/mpv.net-portable-x64-5.4.8.0/shaders/Anime4K_3.0_Upscale_CNN_M_x2_Deblur.glsl"
```

**Comment by Shashank066** [comment]
Thank you, that explains it. `glsl-shaders` worked perfectly.

**Comment by fbriere** [comment]
Reopening -- I won't be satisfied until this bug has been thoroughly fixed.  :smile:

**Comment by fbriere** [comment]
> Indeed, this issue will occur with mpv from 0.29.0 onwards (since [mpv-player/mpv@5532d8c](https://github.com/mpv-player/mpv/commit/5532d8c))

For the record, this actually went all the way back to 0.26.0, due to mpv-player/mpv#7784.
